amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

mysql:
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  schema: ${MYSQL_SCHEMA}
  url: ${MYSQL_URL}:${MYSQL_PORT}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none