amqp:
  admin:
    auto-created: true
  host: localhost
  port: 5672
  username: videos_adm
  password: 123456

mysql:
  username: root
  password: 123456
  schema: videos_adm
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2