version: '3.7'

services:
  app:
    container_name: video_adm_app
    build: .
    profiles:
      - "app"
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - videos_adm_network

  mysql:
    container_name: videos_adm_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=videos_adm
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - videos_adm_network

  rabbitmq:
    container_name: videos_adm_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=videos_adm
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - videos_adm_network

networks:
  videos_adm_network: