version: '3.7'

services:
  mysql:
    container_name: videos_adm_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=videos_adm
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - videos_adm_network

networks:
  videos_adm_network: